name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - run: npm ci && npm run build
      - run: npm run check
        env:
          # https://github.com/parcel-bundler/parcel/issues/8005
          NODE_OPTIONS: --no-experimental-fetch
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - run: npm ci && npm run build
      - run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 17.x
      - run: npm ci && npm run build
      - run: npm run test
